printf " 💻 Hostname : %s\n" "$(hostname)"
printf " 🐧 Kernel   : %s\n" "$(uname -r)"
printf " 🏗️ Build    : %s\n" "$(uname -v)"
printf " 🧠 Memory   : %s\n" "$(free -h | awk '/Mem:/ {print $3 "/" $2}')"
printf " 📦 Disk     : %s\n" "$(df -h / | awk 'NR==2 {print $3 "/" $2 " used"}')"
printf "\nHave a great day, hacker! 🚀\n\n"